[package]
name = "cdrs-tokio-astra"
version = "0.1.0"
authors = ["jac3km4 <jac3km4@pm.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cdrs-tokio = { version = "4.0", features = ["rust-tls"] }
rustls = "0.19"
rustls-pemfile = "0.2"
webpki = "0.21"
